apiVersion: v1
kind: Service
metadata:
  name: examen-devops-service
spec:
  type: NodePort # Perfect for local testing clusters like Minikube/Kind
  selector:
    app: ticket-api
  ports:
    - protocol: TCP
      port: 80       # Port exposed inside the cluster
      targetPort: 8000 # Port the FastAPI app runs on inside the container
      nodePort: 30080 # Port accessible from your web browser locally
