apiVersion: apps/v1
kind: Deployment
metadata:
  name: examen-devops-deployment
  labels:
    app: ticket-api
spec:
  replicas: 2 # Launches two parallel instances for high availability
  selector:
    matchLabels:
      app: ticket-api
  template:
    metadata:
      labels:
        app: ticket-api
    spec:
      containers:
      - name: ticket-api-container
        image: examen-devops:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
